### ISSUE TITLE
Access denied from IE or Edge

### ISSUE THREAD

**Issue by perryk** [clonemeagain/attachment_preview#19]
This isn't something I tested myself, however I have an Agent using IE and they receive this popup just after clicking on a ticket that will use this plugin, however it shows before the ticket page opens. They can just click ok, and then the ticket is displayed ok, however, the plugin doesn't display the attachment.

![image001](https://user-images.githubusercontent.com/806269/32589113-66f4e160-c55e-11e7-8d7f-483e0f159343.png)

**Comment by clonemeagain** [comment]
I try and avoid testing anything on IE 😨 .. the object embed code wouldn't have worked, so I just sort of.. ignored it. :-| IE won't embed it how I wanted, so it should be showing an error message "Get a better browser" etc. However that is configurable.  Oh, nope, just tested it in IE, and that doesn't show up, because the script simply deletes the element. My bad. (patched).

Just got Adobe installed as well. 💩  (because of the title of that popup). 
No dice. 

Based on this: https://stackoverflow.com/questions/30810246/access-is-denied-when-embedding-file-from-blob-url-in-ie
The answer is: No, can't happen. 

Fixed the popup error though.

**Comment by perryk** [comment]
Thanks, yes I felt bad logging the issue even!

All good, I'll try out the changes over the weekend. The agent isn't all that worried and fixing the popup will mean everything else works which is great.

Cheers.

**Comment by perryk** [comment]
This tested out all ok, the option to choose to display the abetterbrowser message is a nice touch.

I noticed IE can still preview attached images, just not the embedded stuff. That is something at least.
