### ISSUE TITLE
enable attachment_preview break display delete button

### ISSUE THREAD

**Issue by visiniaga** [clonemeagain/attachment_preview#42]
checking with awesome osticket 1.12.2
strange that delete button is become smaller, and check with chrome inspection there is break  

"Uncaught SyntaxError: Invalid or unexpected token in tickets.php

![Screenshot 2019-08-14 at 20 22 35](https://user-images.githubusercontent.com/43309334/63025172-d2c44b00-bed2-11e9-95db-ca4d5ee42bf3.jpg)
![Screenshot 2019-08-14 at 20 19 55](https://user-images.githubusercontent.com/43309334/63025173-d3f57800-bed2-11e9-9912-cf56bd8c53b1.jpg)
![Screenshot 2019-08-14 at 18 14 14](https://user-images.githubusercontent.com/43309334/63025175-d3f57800-bed2-11e9-9e9c-3ddd3d281ba0.jpg)

**Comment by visiniaga** [comment]
add condition if the ticket id is correct when checking isTicketsView(), 
to enable attachment_preview only running when correct ticket id is isset.

file include/plugins/attachment_preview/class.AttachmentPreviewPlugin.php
-> line 5
`require_once (INCLUDE_DIR . 'class.ticket.php');` 

-> line 1060
`elseif ($_REQUEST['id'] && ($ticket=Ticket::lookup($_REQUEST['id']))) {`
`       $tickets_view = TRUE;`
`    }`


-> comment line 1063-1067
`     #elseif (strpos($url, 'index.php') !== FALSE ||`
`     #  strpos($url, 'tickets.php') !== FALSE) {`
`       // Might be a ticket page..`
`     #  $tickets_view = TRUE;`
`     #}`

**Comment by clonemeagain** [comment]
Wouldn't that match any url that included any id parameter? 
The original formula is intended to only match GET parameters.

I've not tested 1.12 yet, but will soon.

**Comment by visiniaga** [comment]
yes, checking what whould have condition for tickets is viewing or others.
get id and it require valid id.

checking for task also worked 
added for `require_once (INCLUDE_DIR . 'class.task.php');`
and
`elseif ($_REQUEST['id'] && ($ticket=Task::lookup($_REQUEST['id']))) { `
`$tickets_view = TRUE; `
`}  `

**Comment by clonemeagain** [comment]
The $_REQUEST global includes all POST data and GET data. I wanted to avoid that, as the number of instances where there is a valid ticket id, but not a visible page/attachment, ie: Printing, AJAX, saving things..
Hence the specific usages of POST and GET in the filter.

Not sure of the value of instantiating either a Ticket or Task in a static method which would throw it away.. on every run of anything osTicket. This would increase the load unnecessarily. Also, adding a task dependency would ruin any backwards compatibility.. a string should suffice there.

Also, if that doesn't match, then it shouldn't be changing anything.. so, why would changing that to run now cause it to break? Sounds more serious mate. Because it's obviously running, therefore it is unlikely to be that matcher being an issue.

What was the invalid token in your page? I mean, the screenshot of the highlighted page is cool and all, but it doesn't actually show the error..  

You seem to be using a non-standard "theme".. so might have additional issues using plugins developed for the original program, which would require additional debugging details to be shared. I do not have access to that program (the "theme" is a reskinned entire copy, so it's quite different), so am unable to replicate exactly. If you are able to get the same problem with standard osTicket I'll look into it.
